language: ruby
rvm:
#  - 1.8.7
  - 1.9.3
#  - jruby-18mode
#  - jruby-19mode
#  - rbx-18mode
#  - rbx-19mode

install:
  - sudo apt-get install subversion mercurial
  - bundle version
  - bundle install
  - bundle list

script: bundle exec ruby -W0 test/runner.rb -v

#branches:
#  only:
#    - master

